export const FETCHING_KEY_DATA = "FETCHING_KEY_DATA";
export const FETCHING_KEY_DATA_SUCCESS = "FETCHING_KEY_DATA_SUCCESS";
export const FETCHING_KEY_DATA_FAIL = "FETCHING_KEY_DATA_FAIL";

export const TOGGLE_CELL = "TOGGLE_CELL";
export const TICK = "TICK";
export const START_SIMULATION = "START_SIMULATION";
export const STOP_SIMULATION = "STOP_SIMULATION";
export const CLEAR = "CLEAR";